# Generated by Django 5.1.1 on 2025-07-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(max_length=256, unique=True)),
                (
                    "friendly_name",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=256, null=True)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "has_sizes",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("specs", models.JSONField(default=dict)),
                ("stock", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="shop/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
