# Generated by Django 5.1.1 on 2025-07-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="friendly_name",
        ),
    ]
